//! Stage 2b: real mainnet blocks through both oracles, three tiers.
//!
//! The fixtures are gitignored (66 MB of raw block hex) and regenerated by
//! `scripts/measure_baseline.sh`. Tests **skip** rather than fail when they are
//! absent, so CI stays green on a checkout without them — but a skipped test
//! prints why, and a green run is not evidence these executed.
//!
//! The checkpoint files *are* committed, so tier 3 needs no node.

#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::panic,
    clippy::unwrap_used
)]

use std::path::PathBuf;

use zebra_chain::block::Block;
use zebra_chain::serialization::ZcashDeserialize;

use zutreexo_testkit::harness::{replay, Divergence, Fault, HarnessConfig};

const SLICES: [&str; 4] = [
    "sapling-activation",
    "nu5-orchard",
    "sandblasting",
    "ironwood-activation",
];

/// Depth for the differential replay.
///
/// Below `MAX_NAIVE_DEPTH` because the oracle materialises `2^depth` leaves by
/// design. Depth is a parameter, so structural agreement here is the same
/// statement as agreement at the production depth of 40.
///
/// # Why this is tunable, and why the default is not the tightest setting
///
/// A cold root rebuild costs about `2^(depth+1)` hashes, per pool, per check.
/// At depth 14 with a check after every block that is roughly 10^8 hashes
/// across the four slices — fine in release, but `cargo test` builds
/// unoptimised, and it turns a CI job into a twenty-minute one. A check that
/// slow gets run less often, which costs more correctness than the tighter
/// setting buys.
///
/// So the default is cheap enough to run on every push, and the nightly sweep
/// raises both knobs to their strictest. Override locally when bisecting:
///
/// ```text
/// ZUTREEXO_HARNESS_DEPTH=14 ZUTREEXO_ROOT_CHECK_EVERY=1 cargo test --release ...
/// ```
/// # Why not lower
///
/// Capacity is `2^depth` leaves *per pool*, and the Ironwood slice alone
/// reveals 5,838 Orchard nullifiers in 200 blocks. Depth 12 holds 4,096, so the
/// Orchard tree fills at block 130 and both sides start rejecting in lockstep —
/// agreement, not divergence, but not a complete replay either. Depth 14 holds
/// 16,384, which clears the largest slice with room to spare.
const DEFAULT_DEPTH: u8 = 14;

/// Blocks between tier 2 rebuilds. `1` checks after every block.
const DEFAULT_ROOT_CHECK_EVERY: u32 = 10;

fn env_u32(key: &str, fallback: u32) -> u32 {
    std::env::var(key)
        .ok()
        .and_then(|value| value.parse().ok())
        .unwrap_or(fallback)
}

fn depth() -> u8 {
    let value = env_u32("ZUTREEXO_HARNESS_DEPTH", u32::from(DEFAULT_DEPTH));
    u8::try_from(value).unwrap_or(DEFAULT_DEPTH)
}

fn root_check_every() -> u32 {
    env_u32("ZUTREEXO_ROOT_CHECK_EVERY", DEFAULT_ROOT_CHECK_EVERY)
}

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("fixtures")
}

fn repro_dir() -> PathBuf {
    std::env::temp_dir().join("zutreexo-repro")
}

fn load_slice(name: &str) -> Option<Vec<Block>> {
    let path = fixture_dir().join(format!("{name}.jsonl"));
    let text = std::fs::read_to_string(&path).ok()?;

    let mut blocks = Vec::new();
    for (line_no, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let hex_str = line.trim_matches('"');
        let bytes =
            hex::decode(hex_str).unwrap_or_else(|e| panic!("{name} line {line_no}: bad hex: {e}"));
        let block = Block::zcash_deserialize(&bytes[..])
            .unwrap_or_else(|e| panic!("{name} line {line_no}: bad block: {e}"));
        blocks.push(block);
    }
    Some(blocks)
}

fn skip(name: &str) {
    eprintln!(
        "SKIPPED: fixtures/{name}.jsonl not present. \
         Regenerate with scripts/measure_baseline.sh against a synced node."
    );
}

fn config(name: &str) -> HarnessConfig {
    HarnessConfig {
        depth: depth(),
        root_check_every: root_check_every(),
        repro_dir: Some(repro_dir()),
        allow_unknown_spends: true,
        enforce_contiguous: true,
        label: name.to_owned(),
        fault: None,
    }
}

/// The stage 2b milestone: every fixture slice replays with all three tiers
/// green, roots compared after *every* block.
#[test]
fn every_slice_agrees_with_both_oracles() {
    let mut ran = 0;
    for name in SLICES {
        let Some(blocks) = load_slice(name) else {
            skip(name);
            continue;
        };

        let report = replay(&blocks, &config(name))
            .unwrap_or_else(|divergence| panic!("{name}: {divergence}"));

        // Checked before the block count, because it explains it: a truncated
        // replay is almost always a pool running out of capacity, and the
        // count assertion alone would just say "130, expected 200".
        assert_eq!(
            report.stopped_early, None,
            "{name}: replay did not consume the whole slice"
        );
        assert_eq!(report.blocks, 200, "{name}: not every block applied");

        // Tier 2 runs every N blocks plus always on the last. Asserting the
        // exact count keeps a silently-disabled tier from passing as green.
        let n = root_check_every();
        let expected_checks = (200 / n as usize) + usize::from(200 % n as usize != 0);
        assert_eq!(
            report.root_checks, expected_checks,
            "{name}: tier 2 ran {} times, expected {expected_checks} at N={n}",
            report.root_checks
        );
        assert!(report.root_checks > 0, "{name}: tier 2 never ran");

        assert_eq!(
            report.checkpoint.as_deref(),
            Some(name),
            "{name}: tier 3 did not run — is the checkpoint file committed?"
        );

        eprintln!(
            "{name}: {} blocks, {} root checks (N={n}, depth {}), \
             tier 3 vs zebrad OK, {} pre-window spends",
            report.blocks,
            report.root_checks,
            depth(),
            report.unknown_spends
        );
        ran += 1;
    }

    if ran == 0 {
        eprintln!("SKIPPED: no fixtures present, nothing was verified");
    }
}

/// Tier 3 in isolation: our parser's totals against the node's own JSON.
///
/// This is the check that catches a mis-read block, which the naive oracle
/// structurally cannot — it is fed from the same parse.
#[test]
fn parser_totals_match_the_node() {
    for name in SLICES {
        let Some(blocks) = load_slice(name) else {
            skip(name);
            continue;
        };

        let checkpoint = zutreexo_testkit::checkpoints::load(name).unwrap();
        let report = replay(&blocks, &config(name)).unwrap();

        // Without this, a truncated replay reports fewer of everything and the
        // failure reads as a parser disagreement rather than as what it is.
        assert_eq!(
            report.stopped_early, None,
            "{name}: replay truncated, so these totals are not comparable"
        );

        for (field, expected) in &checkpoint.totals {
            let actual = report.totals.get(field).copied();
            if let Some(actual) = actual {
                assert_eq!(
                    actual, *expected,
                    "{name}: our parser says {field} = {actual}, zebrad says {expected}"
                );
            }
        }
        eprintln!(
            "{name}: parser agrees with zebrad on {} fields",
            checkpoint.totals.len()
        );
    }
}

/// A pool running out of capacity must be reported, not mistaken for a clean
/// short replay.
///
/// Found the hard way: at depth 12 the Orchard tree holds 4,096 leaves and the
/// Ironwood slice reveals 5,838 Orchard nullifiers, so both the implementation
/// and the oracle start rejecting at block 130. That is *agreement*, so it is
/// not a divergence — and the run looked like a clean pass over 130 blocks.
#[test]
fn a_full_tree_is_reported_rather_than_silently_truncating() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };

    let mut cfg = config(name);
    cfg.depth = 12; // deliberately too small: 4,096 < 5,838

    let report = replay(&blocks, &cfg).expect("filling a tree is agreement, not a divergence");

    assert!(
        report.blocks < 200,
        "depth 12 should not fit the Ironwood slice; did capacity change?"
    );
    let reason = report
        .stopped_early
        .expect("a truncated replay must say why it stopped");
    assert!(
        reason.contains("4096"),
        "the message should name the capacity that was exceeded: {reason}"
    );
    eprintln!("truncation correctly reported: {reason}");
}

/// Determinism, CLAUDE.md §5 rule 5.
#[test]
fn replay_is_deterministic() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };
    let first = replay(&blocks, &config(name)).unwrap();
    let second = replay(&blocks, &config(name)).unwrap();
    assert_eq!(first, second, "{name}: replay is not deterministic");
}

// ---------------------------------------------------------------------------
// Fault injection: proving each tier actually fires.
//
// A harness that has never caught anything is unproven. Each test below injects
// a corruption into the implementation's input only — the oracle still sees the
// truth — so the injected fault is indistinguishable from a real bug.
// ---------------------------------------------------------------------------

fn first_slice_with_nullifiers() -> Option<(&'static str, Vec<Block>)> {
    for name in SLICES {
        if let Some(blocks) = load_slice(name) {
            return Some((name, blocks));
        }
    }
    None
}

/// A dropped nullifier changes counts, so the cheap every-block tier catches it
/// immediately.
#[test]
fn tier_1_catches_a_dropped_nullifier() {
    let Some((name, blocks)) = first_slice_with_nullifiers() else {
        skip("any");
        return;
    };

    // Pick a height that actually reveals a nullifier, or the fault is a no-op.
    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        (summary.nullifier_count() > 0).then_some(summary.height)
    }) else {
        eprintln!("SKIPPED: no block in {name} reveals a nullifier");
        return;
    };

    let mut cfg = config(name);
    cfg.fault = Some(Fault::DropNullifier { height });

    match replay(&blocks, &cfg) {
        Err(Divergence::Counts { field, .. }) => {
            assert!(field.ends_with("_nullifiers"), "wrong field: {field}");
        }
        Err(other) => panic!("expected a tier 1 count divergence, got: {other}"),
        Ok(_) => panic!("tier 1 did not catch a dropped nullifier at height {height}"),
    }
}

/// A dropped output likewise changes counts.
#[test]
fn tier_1_catches_a_dropped_output() {
    let Some((name, blocks)) = first_slice_with_nullifiers() else {
        skip("any");
        return;
    };

    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        (!summary.transparent_creates.is_empty()).then_some(summary.height)
    }) else {
        eprintln!("SKIPPED: no block in {name} creates an output");
        return;
    };

    let mut cfg = config(name);
    cfg.fault = Some(Fault::DropCreate { height });

    match replay(&blocks, &cfg) {
        Err(Divergence::Counts { field, .. }) => assert_eq!(field, "utxos"),
        Err(other) => panic!("expected a tier 1 count divergence, got: {other}"),
        Ok(_) => panic!("tier 1 did not catch a dropped output at height {height}"),
    }
}

/// **The test that justifies tier 2's cost.**
///
/// Reordering nullifiers within a pool leaves every count identical, so tier 1
/// is structurally blind to it. Only the leaf indices move — and that changes
/// the root. If this test ever starts failing with `Ok`, tier 2 has stopped
/// working and the harness has quietly lost the only check that catches
/// order-dependent drift.
#[test]
fn tier_2_catches_a_reordering_that_tier_1_cannot_see() {
    let Some((name, blocks)) = first_slice_with_nullifiers() else {
        skip("any");
        return;
    };

    // Needs a block with at least two nullifiers in one pool; reversing a
    // single-element list is a no-op.
    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        let reorderable = zutreexo_chain::PoolId::ALL
            .into_iter()
            .any(|pool| summary.nullifiers_for(pool).len() >= 2);
        reorderable.then_some(summary.height)
    }) else {
        eprintln!("SKIPPED: no block in {name} has two nullifiers in one pool");
        return;
    };

    let mut cfg = config(name);
    cfg.fault = Some(Fault::ReorderNullifiers { height });

    match replay(&blocks, &cfg) {
        Err(Divergence::Root {
            pool,
            actual,
            expected,
            ..
        }) => {
            assert_ne!(actual, expected);
            eprintln!("tier 2 caught the reordering in the {pool} tree, as designed");
        }
        Err(Divergence::Counts {
            field,
            actual,
            expected,
            ..
        }) => panic!(
            "a reordering changed counts ({field}: {actual} vs {expected}) — \
             the fault is not testing what it claims to"
        ),
        Err(other) => panic!("expected a tier 2 root divergence, got: {other}"),
        Ok(_) => panic!(
            "tier 2 did not catch a nullifier reordering at height {height}. \
             The load-bearing tier is not working."
        ),
    }
}

/// Tier 1 must be blind to the reordering, or the test above proves nothing
/// about tier 2.
#[test]
fn tier_1_is_provably_blind_to_a_reordering() {
    let Some((name, blocks)) = first_slice_with_nullifiers() else {
        skip("any");
        return;
    };

    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        zutreexo_chain::PoolId::ALL
            .into_iter()
            .any(|pool| summary.nullifiers_for(pool).len() >= 2)
            .then_some(summary.height)
    }) else {
        return;
    };

    let mut cfg = config(name);
    cfg.fault = Some(Fault::ReorderNullifiers { height });
    // Disable tier 2 entirely, leaving only counts.
    cfg.root_check_every = 0;

    // With tier 2 off, the replay runs to completion despite the corruption.
    // That is the point: counts alone would have shipped this bug.
    match replay(&blocks, &cfg) {
        Ok(report) => {
            assert_eq!(report.blocks, 200);
            eprintln!(
                "tier 1 alone accepted a corrupted replay of {name} — \
                 which is exactly why tier 2 exists"
            );
        }
        Err(Divergence::Root { .. }) => {
            panic!("tier 2 ran despite root_check_every = 0")
        }
        Err(other) => panic!("unexpected divergence with tier 2 disabled: {other}"),
    }
}

/// **The test that justifies tier 3's existence.**
///
/// Undercounting a note commitment is a *parsing* bug, not an accumulator one.
/// Commitments are counted and never accumulated, so they touch no root and no
/// count that tier 1 or tier 2 compares — and both oracles are fed from the same
/// parse, so neither can notice. Only the node's own answer disagrees.
#[test]
fn tier_3_catches_a_parsing_bug_neither_local_tier_can_see() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };

    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        let has_commitments = zutreexo_chain::PoolId::ALL
            .into_iter()
            .any(|pool| summary.commitments_for(pool) > 0);
        has_commitments.then_some(summary.height)
    }) else {
        eprintln!("SKIPPED: no block in {name} creates a note commitment");
        return;
    };

    let mut cfg = config(name);
    cfg.fault = Some(Fault::DropCommitment { height });

    match replay(&blocks, &cfg) {
        Err(Divergence::Checkpoint {
            field,
            actual,
            expected,
            ..
        }) => {
            assert!(field.ends_with("_commitments"), "wrong field: {field}");
            assert_eq!(
                actual + 1,
                expected,
                "exactly one commitment should have gone missing"
            );
            eprintln!("tier 3 caught the miscount in {field}, as designed");
        }
        Err(other) => panic!("expected a tier 3 checkpoint divergence, got: {other}"),
        Ok(_) => panic!(
            "tier 3 did not catch a commitment miscount at height {height}. \
             The parsing oracle is not working."
        ),
    }
}

/// Tiers 1 and 2 must be blind to that miscount, or the test above proves
/// nothing about tier 3 specifically.
#[test]
fn local_tiers_are_provably_blind_to_a_commitment_miscount() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };

    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        zutreexo_chain::PoolId::ALL
            .into_iter()
            .any(|pool| summary.commitments_for(pool) > 0)
            .then_some(summary.height)
    }) else {
        return;
    };

    // Point the label at a slice with no checkpoint file, which disables tier 3
    // and leaves only the two local tiers running.
    let mut cfg = config(name);
    cfg.label = "no-checkpoint-for-this".to_owned();
    cfg.fault = Some(Fault::DropCommitment { height });

    match replay(&blocks, &cfg) {
        Ok(report) => {
            assert_eq!(report.blocks, 200);
            assert_eq!(report.checkpoint, None, "tier 3 should not have run");
            eprintln!(
                "tiers 1 and 2 accepted a corrupted parse — \
                 which is exactly why tier 3 exists"
            );
        }
        Err(other) => panic!("a local tier saw a commitment miscount it cannot see: {other}"),
    }
}

/// A divergence must leave behind a repro that can be loaded back without a
/// node or a fixture directory.
#[test]
fn a_divergence_writes_a_loadable_repro() {
    let Some((name, blocks)) = first_slice_with_nullifiers() else {
        skip("any");
        return;
    };

    let Some(height) = blocks.iter().find_map(|block| {
        let summary = zutreexo_chain::summarize_block(block).ok()?;
        (summary.nullifier_count() > 0).then_some(summary.height)
    }) else {
        return;
    };

    let dir = repro_dir().join("loadable");
    let _ = std::fs::remove_dir_all(&dir);

    let mut cfg = config(name);
    cfg.repro_dir = Some(dir.clone());
    cfg.fault = Some(Fault::DropNullifier { height });

    let divergence = replay(&blocks, &cfg).expect_err("the fault should diverge");

    let entries: Vec<_> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("no repro directory at {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .collect();
    assert_eq!(entries.len(), 1, "expected exactly one repro file");

    let path = entries[0].path();
    let repro = zutreexo_testkit::harness::load_repro(&path)
        .unwrap_or_else(|e| panic!("repro at {} will not load: {e}", path.display()));

    assert_eq!(
        repro.block.coinbase_height().unwrap().0,
        height,
        "the repro records the wrong block"
    );
    assert_eq!(
        repro.divergence,
        divergence.to_string(),
        "the repro records a different divergence than the one returned"
    );
    // The fault must round-trip, or replaying the seed would not reproduce it.
    assert_eq!(repro.config.fault, Some(Fault::DropNullifier { height }));

    let _ = std::fs::remove_dir_all(&dir);
}
