//! Stage 2a milestone: replay real mainnet blocks through `apply_block`.
//!
//! These are the four fixture slices captured in Phase 0 — 200 blocks each at
//! Sapling activation, NU5/Orchard activation, the 2022–23 sandblasting window,
//! and Ironwood activation. Real blocks, real transaction formats, real
//! activation-boundary edge cases.
//!
//! The fixtures are gitignored (65 MB of raw block hex) and regenerated by
//! `scripts/measure_baseline.sh`. Every test here **skips** rather than fails
//! when they are absent, so CI stays green on a checkout without them. A
//! skipped test prints why; do not read a green run as proof these executed.
//!
//! # What is and is not verified here
//!
//! These windows do not start at genesis, so outputs spent inside them were
//! largely created before the window opened. That makes the *transparent*
//! roots meaningless here — `ApplyOptions::window` counts those spends rather
//! than resolving them. The *shielded* side is exact regardless, because
//! inserting a nullifier needs nothing but the nullifier.
//!
//! So: nullifier roots and counts are checked properly. Transparent coverage
//! waits for the genesis-forward replay in stage 2d.
//!
//! # Why this still exists alongside the stage 2b harness
//!
//! `zutreexo-testkit`'s `tests/harness_replay.rs` replays the same slices
//! against two oracles and subsumes most of what is here. It is kept because it
//! tests something the harness structurally cannot: `apply_block` **at depth
//! 32**, close to the production depth of 40.
//!
//! The harness is capped near depth 14, because its oracle materialises
//! `2^depth` leaves and refuses to walk a sparse path — the cleverness it
//! refuses is exactly what would let it share the implementation's bugs. That
//! trade is right for an oracle and it means the harness never exercises a deep
//! tree. This file does, without an oracle. The two are complementary, and
//! neither alone covers both.

// `panic` is allowed here because these helpers run outside `#[test]` bodies,
// where clippy's test exemption does not reach. A malformed fixture is an
// unrecoverable setup error and should abort loudly with the offending line.
#![allow(
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::panic
)]

use std::collections::BTreeMap;
use std::path::PathBuf;

use zebra_chain::block::Block;
use zebra_chain::serialization::ZcashDeserialize;

use zutreexo_chain::{apply_block, summarize_block, ApplyOptions, ChainAccumulators, PoolId};

/// Depth used for these tests. Smaller than `DEFAULT_DEPTH` only to keep the
/// trees cheap; the logic under test does not depend on depth.
const DEPTH: u8 = 32;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("fixtures")
}

/// Loads one fixture slice. Each line is a JSON string of raw block hex.
fn load_slice(name: &str) -> Option<Vec<Block>> {
    let path = fixture_dir().join(format!("{name}.jsonl"));
    let text = std::fs::read_to_string(&path).ok()?;

    let mut blocks = Vec::new();
    for (line_no, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // The line is a JSON string literal; strip the quotes rather than
        // pulling in a JSON parser for a value with no escapes.
        let hex_str = line.trim_matches('"');
        let bytes =
            hex::decode(hex_str).unwrap_or_else(|e| panic!("{name} line {line_no}: bad hex: {e}"));
        let block = Block::zcash_deserialize(&bytes[..])
            .unwrap_or_else(|e| panic!("{name} line {line_no}: bad block: {e}"));
        blocks.push(block);
    }
    Some(blocks)
}

fn skip(name: &str) -> bool {
    eprintln!(
        "SKIPPED: fixtures/{name}.jsonl not present. \
         Regenerate with scripts/measure_baseline.sh against a synced node."
    );
    true
}

const SLICES: [&str; 4] = [
    "sapling-activation",
    "nu5-orchard",
    "sandblasting",
    "ironwood-activation",
];

/// The milestone: every fixture block parses and applies, in order, with no
/// error and no state corruption.
#[test]
fn every_fixture_block_applies() {
    for name in SLICES {
        let Some(blocks) = load_slice(name) else {
            skip(name);
            continue;
        };
        assert_eq!(blocks.len(), 200, "{name}: expected 200 blocks");

        let mut state = ChainAccumulators::new(DEPTH).unwrap();
        let mut applied = 0usize;
        let mut unknown = 0usize;
        let mut nullifiers = 0usize;

        for block in &blocks {
            let summary =
                summarize_block(block).unwrap_or_else(|e| panic!("{name}: summarize failed: {e}"));
            let outcome = apply_block(&mut state, &summary, ApplyOptions::window())
                .unwrap_or_else(|e| panic!("{name} height {}: {e}", summary.height));

            nullifiers += summary.nullifier_count();
            unknown += outcome.unknown_spends;
            applied += 1;
        }

        assert_eq!(applied, 200);
        eprintln!(
            "{name}: 200 blocks, {nullifiers} nullifiers, \
             {unknown} pre-window spends, utxos tracked {}",
            state.utxo_count()
        );
    }
}

/// Nullifier counts extracted by our parser must match what the accumulator
/// actually absorbed. Catches an extraction/apply mismatch.
#[test]
fn nullifier_counts_reconcile() {
    for name in SLICES {
        let Some(blocks) = load_slice(name) else {
            skip(name);
            continue;
        };

        let mut state = ChainAccumulators::new(DEPTH).unwrap();
        let mut expected: BTreeMap<PoolId, u64> = BTreeMap::new();

        for block in &blocks {
            let summary = summarize_block(block).unwrap();
            for pool in PoolId::ALL {
                *expected.entry(pool).or_insert(0) += summary.nullifiers_for(pool).len() as u64;
            }
            apply_block(&mut state, &summary, ApplyOptions::window()).unwrap();
        }

        for pool in PoolId::ALL {
            assert_eq!(
                state.nullifier_count(pool),
                expected[&pool],
                "{name}: {pool} nullifier count diverged"
            );
        }
    }
}

/// Applying the same slice twice must produce identical roots. Determinism is
/// CLAUDE.md §5 rule 5, and a `HashMap` sneaking into a root path is exactly
/// the kind of thing that breaks it intermittently rather than loudly.
#[test]
fn replay_is_deterministic() {
    for name in SLICES {
        let Some(blocks) = load_slice(name) else {
            skip(name);
            continue;
        };

        let run = || {
            let mut state = ChainAccumulators::new(DEPTH).unwrap();
            for block in &blocks {
                let summary = summarize_block(block).unwrap();
                apply_block(&mut state, &summary, ApplyOptions::window()).unwrap();
            }
            state.nullifier_roots()
        };

        assert_eq!(run(), run(), "{name}: replay is not deterministic");
    }
}

/// The parsing oracle, pinned.
///
/// These counts are not guesses and not self-derived. They were cross-checked
/// against `zebrad`'s own JSON rendering of the *same* 200 blocks
/// (`getblock <height> 2`, counting `vjoinsplit`×2, `vShieldedSpend`,
/// `orchard.actions`, `ironwood.actions`), and both paths agreed exactly on all
/// four pools for both nullifiers and commitments.
///
/// That is the check CLAUDE.md Phase 2 wants from the validator oracle: our
/// binary deserializer and Zebra's JSON serializer are independent routes out
/// of the same bytes, so agreement means the parse is right — not merely
/// self-consistent. Two models fed one bad parse would agree with each other
/// and both be wrong; this is what rules that out.
///
/// Pinning the numbers here keeps the check alive without CI needing a synced
/// node. If it fails, the parser changed — re-run the cross-check before
/// touching these constants.
const IRONWOOD_SLICE_NULLIFIERS: [(PoolId, usize); 4] = [
    (PoolId::Sprout, 0),
    (PoolId::Sapling, 28),
    (PoolId::Orchard, 5838),
    (PoolId::Ironwood, 1828),
];

const IRONWOOD_SLICE_COMMITMENTS: [(PoolId, usize); 4] = [
    (PoolId::Sprout, 0),
    (PoolId::Sapling, 50),
    (PoolId::Orchard, 5838),
    (PoolId::Ironwood, 1828),
];

#[test]
fn ironwood_activation_slice_matches_the_node() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };

    let mut totals: BTreeMap<PoolId, usize> = BTreeMap::new();
    let mut commitments: BTreeMap<PoolId, usize> = BTreeMap::new();
    for block in &blocks {
        let summary = summarize_block(block).unwrap();
        for pool in PoolId::ALL {
            *totals.entry(pool).or_insert(0) += summary.nullifiers_for(pool).len();
            *commitments.entry(pool).or_insert(0) += summary.commitments_for(pool);
        }
    }
    eprintln!("{name}: nullifiers {totals:?}");
    eprintln!("{name}: commitments {commitments:?}");

    for (pool, expected) in IRONWOOD_SLICE_NULLIFIERS {
        assert_eq!(
            totals[&pool], expected,
            "{name}: {pool} nullifier count disagrees with the node"
        );
    }
    for (pool, expected) in IRONWOOD_SLICE_COMMITMENTS {
        assert_eq!(
            commitments[&pool], expected,
            "{name}: {pool} commitment count disagrees with the node"
        );
    }

    // Orchard and Ironwood actions carry exactly one nullifier and one
    // commitment each, so these must coincide. Sapling separates them, and in
    // this window does not coincide (28 spends, 50 outputs) — which is the
    // control showing the equality above is a real constraint, not an artifact
    // of counting the same array twice.
    assert_eq!(totals[&PoolId::Orchard], commitments[&PoolId::Orchard]);
    assert_eq!(totals[&PoolId::Ironwood], commitments[&PoolId::Ironwood]);
    assert_ne!(totals[&PoolId::Sapling], commitments[&PoolId::Sapling]);

    assert!(
        totals[&PoolId::Ironwood] > 0,
        "no Ironwood nullifiers in the activation slice — extraction is wrong, \
         or the fixture does not cover activation"
    );
}

/// A block applied twice is a double spend of every nullifier it carries, and
/// must be rejected with the state untouched.
#[test]
fn replaying_a_block_is_rejected() {
    let name = "ironwood-activation";
    let Some(blocks) = load_slice(name) else {
        skip(name);
        return;
    };

    // Find a block that actually reveals nullifiers; an empty one would make
    // this test vacuous.
    let Some(block) = blocks.iter().find(|b| {
        summarize_block(b)
            .map(|s| s.nullifier_count() > 0)
            .unwrap_or(false)
    }) else {
        eprintln!("SKIPPED: no fixture block reveals nullifiers");
        return;
    };

    let summary = summarize_block(block).unwrap();
    let mut state = ChainAccumulators::new(DEPTH).unwrap();

    let mut options = ApplyOptions::window();
    options.enforce_contiguous = false;

    apply_block(&mut state, &summary, options).unwrap();
    let roots_before = state.nullifier_roots();
    let counts_before = state.counts();

    let err =
        apply_block(&mut state, &summary, options).expect_err("replaying a block must be rejected");
    eprintln!("rejected as expected: {err}");

    assert_eq!(
        state.nullifier_roots(),
        roots_before,
        "state mutated on error"
    );
    assert_eq!(state.counts(), counts_before, "counts mutated on error");
}
