//! **The Phase 4a claim:** a node holding only roots reaches the same state as
//! a node holding everything, block for block, given the bridge's proofs.
//!
//! The comparison is byte-identical roots at *every* height, not at the end.
//! An end-only check would pass on a pair of implementations that diverged and
//! happened to reconverge, and would leave the first divergent block unnamed —
//! which is the one piece of information that makes such a bug fixable.
//!
//! # Why the transparent half is synthetic here
//!
//! Deleting a transparent leaf needs the spent output's full contents, which
//! only a genesis-forward replay will have observed. The fixture slices are
//! 200-block windows from the middle of the chain, so nearly every spend in
//! them refers to an output created before the window opened. The bridge
//! cannot prove those and the compact node must not accept them unproven, so
//! the transparent side is exercised against a synthetic chain built from
//! genesis instead — where every spend is resolvable and the roots are exact.
//!
//! Real mainnet blocks still drive the shielded half here, and the full
//! genesis-forward transparent replay lives in `src/bin/csn_replay.rs`.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::collections::BTreeMap;
use std::path::PathBuf;

use zutreexo_accumulator::imt::Value;
use zutreexo_accumulator::{CanonicalSerialize, PoolId, UtxoLeaf};
use zutreexo_chain::{
    apply_and_prove, summarize_block, ApplyOptions, BlockProofBundle, BlockSummary,
    ChainAccumulators, OutPoint,
};
use zutreexo_csn::{CompactState, CsnError};

const DEPTH: u8 = 20;

// ---------------------------------------------------------------------------
// Synthetic chain. Deliberately dumb construction — every block is spelled out
// rather than generated by anything that shares code with the applier.
// ---------------------------------------------------------------------------

fn outpoint(tx: u32, vout: u32) -> OutPoint {
    let mut txid = [0u8; 32];
    txid[..4].copy_from_slice(&tx.to_le_bytes());
    OutPoint { txid, vout }
}

fn leaf(tx: u32, vout: u32, height: u32) -> UtxoLeaf {
    let point = outpoint(tx, vout);
    UtxoLeaf {
        txid: point.txid,
        vout: point.vout,
        height,
        is_coinbase: vout == 0 && tx % 7 == 0,
        value: u64::from(tx) * 1000 + u64::from(vout),
        // Varying length so the length-prefixed encoding is actually exercised.
        script_pubkey: vec![0xac; (tx % 25) as usize],
    }
}

fn nullifier(n: u32) -> Value {
    let mut bytes = [0u8; 32];
    bytes[..4].copy_from_slice(&n.to_le_bytes());
    // Keep the high byte clear of the max-value edge case.
    bytes[31] = 0x01;
    Value::from_bytes(bytes)
}

fn empty_summary(height: u32) -> BlockSummary {
    BlockSummary {
        height,
        transactions: 1,
        transparent_spends: Vec::new(),
        transparent_creates: Vec::new(),
        nullifiers: BTreeMap::new(),
        commitments: BTreeMap::new(),
    }
}

/// A chain from genesis where each block creates outputs, spends some of the
/// previous block's, and reveals nullifiers into rotating pools.
fn synthetic_chain(blocks: u32) -> Vec<BlockSummary> {
    let mut out = Vec::new();
    let mut next_nullifier = 1u32;

    for height in 0..blocks {
        let mut summary = empty_summary(height);
        summary.transactions = 3;

        // Three outputs per block.
        for vout in 0..3u32 {
            summary
                .transparent_creates
                .push((outpoint(height, vout), leaf(height, vout, height)));
        }

        // Spend two of the previous block's three outputs.
        if height > 0 {
            summary.transparent_spends.push(outpoint(height - 1, 0));
            summary.transparent_spends.push(outpoint(height - 1, 2));
        }

        // Every fifth block also creates an output and spends it immediately:
        // the intra-block cancellation case (docs/design.md D21), which is the
        // one the compact node has to infer rather than be told.
        if height % 5 == 4 {
            let point = outpoint(height, 90);
            summary
                .transparent_creates
                .push((point, leaf(height, 90, height)));
            summary.transparent_spends.push(point);
        }

        // Nullifiers into two pools, so ordering across pools is exercised.
        if height % 3 != 0 {
            for pool in [PoolId::Sapling, PoolId::Orchard] {
                let count = (height % 4) + 1;
                let values: Vec<Value> = (0..count)
                    .map(|_| {
                        let v = nullifier(next_nullifier);
                        next_nullifier += 1;
                        v
                    })
                    .collect();
                summary.nullifiers.insert(pool, values);
            }
        }

        out.push(summary);
    }
    out
}

/// Runs bridge and compact node in lockstep, asserting identical roots after
/// every block. Returns the bundles so size can be measured separately.
fn lockstep(summaries: &[BlockSummary]) -> Vec<BlockProofBundle> {
    let mut bridge = ChainAccumulators::new(DEPTH).unwrap();
    let mut csn = CompactState::new(DEPTH).unwrap();
    let mut bundles = Vec::new();

    for summary in summaries {
        let (_, bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default())
            .unwrap_or_else(|e| panic!("bridge failed at height {}: {e}", summary.height));

        // The bundle goes through its wire encoding before the compact node
        // sees it. Testing against the in-memory value would leave the codec
        // untested on the path that actually matters.
        let encoded = bundle.to_bytes();
        let decoded = BlockProofBundle::from_bytes(&encoded).unwrap_or_else(|e| {
            panic!("bundle at height {} would not decode: {e}", summary.height)
        });
        assert_eq!(decoded, bundle, "bundle did not survive its own encoding");

        csn.apply_bundle(summary, &decoded)
            .unwrap_or_else(|e| panic!("compact node rejected height {}: {e}", summary.height));

        assert_eq!(
            csn.utxo_roots(),
            bridge.utxo_roots(),
            "transparent roots diverged at height {}",
            summary.height
        );
        assert_eq!(
            csn.nullifier_roots(),
            bridge.nullifier_roots(),
            "nullifier roots diverged at height {}",
            summary.height
        );
        assert_eq!(csn.tip(), bridge.tip());

        bundles.push(bundle);
    }
    bundles
}

#[test]
fn a_roots_only_node_tracks_the_bridge_exactly() {
    let chain = synthetic_chain(120);
    let bundles = lockstep(&chain);

    // Guard against the test passing by doing nothing: if the chain stopped
    // producing spends or nullifiers, every root comparison above would be
    // comparing two empty accumulators.
    let spends: usize = bundles.iter().map(|b| b.spent.len()).sum();
    let insertions: usize = bundles.iter().map(BlockProofBundle::insertion_count).sum();
    assert!(
        spends > 200,
        "too few transparent spends exercised: {spends}"
    );
    assert!(
        insertions > 200,
        "too few nullifiers exercised: {insertions}"
    );
}

#[test]
fn the_compact_state_does_not_grow_with_the_chain() {
    // The claim is O(1) state, so measure the thing that would betray it: the
    // encoded size of the compact state after a short chain and a long one.
    fn footprint(blocks: u32) -> usize {
        let mut bridge = ChainAccumulators::new(DEPTH).unwrap();
        let mut csn = CompactState::new(DEPTH).unwrap();
        for summary in synthetic_chain(blocks) {
            let (_, bundle) =
                apply_and_prove(&mut bridge, &summary, ApplyOptions::default()).unwrap();
            csn.apply_bundle(&summary, &bundle).unwrap();
        }
        // Roots are the whole state: transparent roots plus one per pool.
        csn.utxo_roots().len() * 32 + csn.nullifier_roots().len() * 32
    }

    let short = footprint(20);
    let long = footprint(200);

    // Utreexo's root count is the population count of the leaf count, so it
    // moves a little; it does not grow with chain length. A linear structure
    // would be an order of magnitude apart over a 10x chain.
    assert!(
        long < short * 2,
        "compact state grew with the chain: {short} bytes at 20 blocks, {long} at 200"
    );
}

// ---------------------------------------------------------------------------
// A hostile bridge. Each of these is a bundle that would make the compact node
// disagree with the network if it were accepted.
// ---------------------------------------------------------------------------

/// Advances both sides to a point where the next block has real spends, and
/// returns the pieces needed to tamper with it.
fn at_a_spending_block() -> (ChainAccumulators, CompactState, Vec<BlockSummary>) {
    let chain = synthetic_chain(12);
    let mut bridge = ChainAccumulators::new(DEPTH).unwrap();
    let mut csn = CompactState::new(DEPTH).unwrap();
    for summary in &chain[..11] {
        let (_, bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();
        csn.apply_bundle(summary, &bundle).unwrap();
    }
    (bridge, csn, chain)
}

#[test]
fn a_substituted_leaf_is_rejected() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    // Swap in a different output that is genuinely in the accumulator. The
    // inclusion proof no longer matches, but the point is that even if it did,
    // the outpoint check fires first.
    assert!(!bundle.spent.is_empty());
    bundle.spent[0] = leaf(9, 1, 9);

    assert!(matches!(
        csn.apply_bundle(summary, &bundle),
        Err(CsnError::UnprovenSpend { .. })
    ));
}

#[test]
fn an_omitted_spend_is_rejected() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    // Drop a leaf. A node that inferred cancellation from absence alone would
    // quietly skip a deletion and diverge from the network several blocks
    // later, which is why absence is checked against the block.
    bundle.spent.remove(0);

    assert!(matches!(
        csn.apply_bundle(summary, &bundle),
        Err(CsnError::UnprovenSpend { .. })
    ));
}

#[test]
fn a_smuggled_extra_leaf_is_rejected() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    bundle.spent.push(leaf(9, 1, 9));

    assert!(matches!(
        csn.apply_bundle(summary, &bundle),
        Err(CsnError::UnclaimedLeaves { extra: 1, .. })
    ));
}

#[test]
fn a_forged_inclusion_proof_is_rejected() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    // A proof from a different block, which is well-formed but wrong.
    let mut other = ChainAccumulators::new(DEPTH).unwrap();
    for s in &chain[..6] {
        apply_and_prove(&mut other, s, ApplyOptions::default()).unwrap();
    }
    let (_, stale) = apply_and_prove(&mut other, &chain[6], ApplyOptions::default()).unwrap();
    bundle.utxo_proof = stale.utxo_proof;

    assert!(csn.apply_bundle(summary, &bundle).is_err());
}

#[test]
fn a_missing_nullifier_proof_is_rejected() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    assert!(
        bundle.insertion_count() > 0,
        "block has no nullifiers to drop"
    );
    if let Some(proofs) = bundle.insertions.get_mut(&PoolId::Sapling) {
        proofs.pop();
    }

    assert!(matches!(
        csn.apply_bundle(summary, &bundle),
        Err(CsnError::InsertionCountMismatch { .. })
    ));
}

#[test]
fn a_rejected_block_leaves_the_state_untouched() {
    let (mut bridge, mut csn, chain) = at_a_spending_block();
    let summary = &chain[11];
    let (_, mut bundle) = apply_and_prove(&mut bridge, summary, ApplyOptions::default()).unwrap();

    let roots_before = csn.utxo_roots();
    let nullifiers_before = csn.nullifier_roots();
    let tip_before = csn.tip();

    bundle.spent.push(leaf(9, 1, 9));
    assert!(csn.apply_bundle(summary, &bundle).is_err());

    assert_eq!(
        csn.utxo_roots(),
        roots_before,
        "a rejected block mutated the transparent roots"
    );
    assert_eq!(
        csn.nullifier_roots(),
        nullifiers_before,
        "a rejected block mutated a nullifier root"
    );
    assert_eq!(csn.tip(), tip_before);
}

// ---------------------------------------------------------------------------
// Real mainnet blocks, shielded half.
// ---------------------------------------------------------------------------

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("fixtures")
}

fn load_slice(name: &str) -> Option<Vec<zebra_chain::block::Block>> {
    use zebra_chain::serialization::ZcashDeserialize;
    let text = std::fs::read_to_string(fixture_dir().join(format!("{name}.jsonl"))).ok()?;
    let mut blocks = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let bytes = hex::decode(line.trim_matches('"')).expect("bad hex in fixture");
        blocks.push(zebra_chain::block::Block::zcash_deserialize(&bytes[..]).expect("bad block"));
    }
    Some(blocks)
}

/// Real mainnet nullifiers, driven through the bundle and verified from roots
/// alone.
///
/// The transparent fields are cleared rather than tolerated. A window replay
/// cannot resolve spends that predate it, and rather than teach the compact
/// node to accept unproven deletions for the sake of a test — which would
/// weaken the one property this crate exists to provide — the test restricts
/// itself to the half that is exact over a window.
#[test]
fn real_mainnet_nullifiers_verify_from_roots_alone() {
    let mut ran = 0usize;
    for name in [
        "sapling-activation",
        "nu5-orchard",
        "sandblasting",
        "ironwood-activation",
    ] {
        let Some(blocks) = load_slice(name) else {
            eprintln!("SKIPPED {name}: fixture not present");
            continue;
        };

        let mut bridge = ChainAccumulators::new(DEPTH).unwrap();
        let mut csn = CompactState::new(DEPTH).unwrap();
        let mut nullifiers = 0usize;

        for (index, block) in blocks.iter().enumerate() {
            let mut summary = summarize_block(block).expect("fixture block would not parse");
            // Renumber to a contiguous chain from zero: the slice starts
            // mid-chain and both sides enforce contiguity.
            summary.height = index as u32;
            summary.transparent_spends.clear();
            summary.transparent_creates.clear();

            nullifiers += summary.nullifier_count();

            let (_, bundle) = apply_and_prove(&mut bridge, &summary, ApplyOptions::default())
                .unwrap_or_else(|e| panic!("{name} block {index}: bridge failed: {e}"));
            let wire = BlockProofBundle::from_bytes(&bundle.to_bytes()).unwrap();
            csn.apply_bundle(&summary, &wire)
                .unwrap_or_else(|e| panic!("{name} block {index}: compact node rejected: {e}"));

            assert_eq!(
                csn.nullifier_roots(),
                bridge.nullifier_roots(),
                "{name}: nullifier roots diverged at block {index}"
            );
        }

        assert!(nullifiers > 0, "{name}: no nullifiers exercised");
        eprintln!("{name}: {nullifiers} nullifiers verified from roots alone");
        ran += 1;
    }

    if ran == 0 {
        eprintln!("SKIPPED: no fixtures present; this test verified nothing.");
    }
}
